import Head from 'next/head'
import FirstLayout from "../components/FirstLayout/FirstLayout";
import SecondLayout from "../components/SecondLayout/SecondLayout";

export default function Home() {
    return (
        <>
            <Head>
                <title>Grid Practice</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/images/favicon-32x32.png"/>
            </Head>

            {/*<FirstLayout/>*/}
            <SecondLayout/>
        </>
    )
}
